### ISSUE TITLE
Support Jest 28

### ISSUE THREAD

**Issue by thanhsonng** [nvh95/jest-preview#107]
**Which feature you want to improve?**
The [migration guide](https://jestjs.io/docs/upgrading-to-jest28) includes some breaking changes, one of which is the [return value of custom tranformers](https://jestjs.io/docs/upgrading-to-jest28#transformer). They now need to return an object `{ code: '...' }` instead of a string.

**What and why you want to improve that feature**
Jest Preview is compatible with Jest 27. We need to support the latest version (which was just released) as well.

**Comment by nvh95** [comment]
Some questions for discussion:
- Does Jest < 28 work with
```js
  process(sourceText, sourcePath, options) {
   return {
     code: ...
   };
  }
```
?
- Can we somehow have some tests to make sure this change does not break Jest with lower versions? (automatically, not manually test multiple versions)
- Looks like Jest 28 ships quite a number of changes. Is there anything else we need to look into?
@thanhsonng Would you like to open a PR for this?

**Comment by thanhsonng** [comment]
@nvh95 I can't answer any of your questions now, but I will look further let you know as soon as I can. I only discovered this issue from my usage of Jest 28 in the Remix example.

**Comment by nvh95** [comment]
@thanhsonng Sure. I will also take a look for those questions as well. Thanks for raising issues with Jest 28.

**Comment by thanhsonng** [comment]
About the question of whether Jest < 28 works with `{ code }` as the return value's shape of `process`.

The answer is yes. I looked into [Jest version `24.0.0`](https://github.com/facebook/jest/blob/665a93eec70c4f2d7809d1848fbc8ca60cfd8361/types/Transform.js#L50) (just to be sure. [CRA 4 uses Jest `26.6.0`](https://github.com/facebook/create-react-app/blob/v4.0.0/package.json#L33)), and it does support that interface, all the way up to version 28.

<img width="498" alt="Screen Shot 2022-05-22 at 00 32 07" src="https://user-images.githubusercontent.com/28614996/169662847-00da4eec-44a1-44a6-8f9e-a9621dbf6dae.png">

**Comment by nvh95** [comment]
@thanhsonng Would you want to open a PR?
