### ISSUE TITLE
Notify that a new version is available

### ISSUE THREAD

**Issue by nvh95** [nvh95/jest-preview#109]
**Is your feature request related to a problem? Please describe.**
Jest Preview is currently at version < 1.0.0. That means versions with bug fixes and features come pretty frequently. However, once users install a package, they rarely update to a newer version. So we need a way to encourage them to update to the latest version.

**Describe the solution you'd like**
Display a banner to users when they run `jest-preview`. The idea is from docusaurus:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/8603085/169082707-c2213400-a8af-414f-b57f-cc76acd77836.png">

**Describe how should jest-preview implements this feature**
Not sure. Digging docusaurus source code at https://github.com/facebook/docusaurus 

**Describe alternatives you've considered**
`npm` can do the same thing. How does it do?

**Comment by duong-le** [comment]
Hi @nvh95, I would love to take on this task. As I can see, Docusaurus uses a 3rd party package called [update-notifier](https://www.npmjs.com/package/update-notifier) for handling new version notifications. This package is also previously used by the famous npm CLI, but [they drop them in the v7 release](https://github.com/npm/cli/pull/1632) and choose to go with their in-house solution. I can see that the package has already provided some basic customization and if we don't need anything other than that then it is good to go.

Here is something you also need to consider:
1. Should we make a config so the user can choose to disable the notification? (in some cases, the user cannot upgrade for some reasons, and they will be bothered every time they run the app)
2. The way this package works is a little bit different. It will check for updates on the first run and the notification will only be displayed in the 2nd run to avoid blocking the CLI usage. If this is not what we want then we need to find another solution.
3. There is a bug that the notification is not displayed consistently. Docusaurus has already provided a [workaround](https://github.com/facebook/docusaurus/pull/5110).
4. The [update checking interval](https://github.com/yeoman/update-notifier#updatecheckinterval). I know it is a background check and it does not slow down the app but what is the reasonable value we should set? Should we go with the default config (1 day)?

Other than that I think it is a great fit solution. What is your thought?

**Comment by nvh95** [comment]
Hello @duong-le. It's great to see you again and we have a chance to work with each others together.

I love to have you work on this feature. It's super thoughtful of you to design a feature with user-centric mindset and potential hidden issues in the future.

I can review your comment one more time tomorrow to have a better understanding on what you are concerning and give you my thoughts. In the mean time, just proceed with any solution you have in mind. Create a draft PR as soon as possible so I can follow your work and easily support if needed.

Cheers. I can't wait to welcome you to contributors!
