### ISSUE TITLE
File paths don't match between Windows and Unix in Snapshots

### ISSUE THREAD

**Issue by nunocasteleira** [nvh95/jest-preview#117]
**Describe the bug**
I have a snapshot that replaces a component with its full path. I created a snapshot on Windows. When running the tests on Jenkins, the test fails, like this:
```diff
<svg>
-  /src/assets/svg/calendar.svg
+  \src\assets\svg\calendar.svg
</svg>
```

Before implementing jest-preview, this test only had the name of the file:
```
<svg>
  calendar.svg
</svg>
```

**Environment (please complete the following information)**

- OS: macOS 12.2.1, Windows 11, Ubuntu 20
- Jest version: 27.5.1

**Comment by nvh95** [comment]
Thank you @nunocasteleira, can you provide test code, or minimum producible repo, it would help a lot to quickly identify and fix this issue. Thanks.

**Comment by nunocasteleira** [comment]
Will try to create a MVP with the bug as soon as possible.

**Comment by nvh95** [comment]
@nunocasteleira 
> Will try to create a MVP with the bug as soon as possible.

Thank you very much.

For your information that the name of SVG change from just the `filename` to a `full-path` is expected. By this way, Jest Preview can preview it in the browser.

**Comment by nvh95** [comment]
@nunocasteleira Yes. That should be a approach to fix. So I'm asking you to provide a minimum reproducible repo so I can investigate and verify that I actually fix the bug. 😬😬
Fun fact: I'm borrowing a windows computer to work on this issue 🪟 😬😬

**Comment by nvh95** [comment]
If you are interested. I'm happy to have you contribute to the project. The fix should lie somewhere in `transform.ts` file

**Comment by nunocasteleira** [comment]
Sure thing, I will try to provide a reproduction asap and I will also look at the `transform.ts` file :)
I'm still in between meetings.

**Comment by nvh95** [comment]
@nunocasteleira We fix this issue in version **0.2.3**. Please update your `jest-preview` by
`npm install jest-preview@latest` and confirm if this issue has been fixed. Then this issue can be closed. Thanks.

**Comment by nvh95** [comment]
@nunocasteleira Please let us know if you still experience this bug. Thanks.

**Comment by nvh95** [comment]
@nunocasteleira 
Can you try to clear jest cache then update the snapshot if needed.
```bash
./node_modules/.bin/jest --clearCache
```
I think it's better if you can provide us with a minimum reproduction. It would super helpful.

**Comment by nunocasteleira** [comment]
Sorry, my company switched my computer, so now I can't reproduce the bug.

**Comment by nvh95** [comment]
@nunocasteleira So I am gonna leave this issue open for a few days. If by any chance you can reproduce. Let us know. Otherwise, we will close this. Thank you for reporting this.

**Comment by nvh95** [comment]
I close this issue now. Please feel free if you can reproduce the bug. Thanks.
@all-contributors please add @nunocasteleira for bug
