### ISSUE TITLE
Depreacate `externalCss` option in `jestPreviewConfigure`

### ISSUE THREAD

**Issue by nvh95** [nvh95/jest-preview#124]
**Which feature you want to improve?**
- Depreacate `externalCss` option in `jestPreviewConfigure`
- Import directly instead

**What and why you want to improve that feature**
- Since we can import `externalCss` directly in the `setupTest.ts` (`setupFilesAfterEnv`)
```diff
+import 'global.css';
+import 'assets/_scss/global-style.scss';

jestPreviewConfigure({
-  externalCss: ['src/global.css', 'src/assets/_scss/global-style.scss'],
  publicFolder: 'src/public',
  autoPreview: true,
});
```

- We don't need to process `.css` file in the `jestPreviewConfigure` anymore. Code to handle `externalCss` in `jestPreviewConfigure` is currently not very clean. 

**Potential bugs/ unexpected behaviors**
Old users who already configure `externalCss` needs to update the setup code. We need to inform them nicely at the terminal/ Or throw an error to force them to use it the right way

**How to implement the changes**
- Find a way to nicely warn them that the feature is deprecated, then give users the blog link to migrate
- (Another option): Harsh experience: if user provides `externalCss` => throw an error and let they know the correct way to import external CSS

**Others**
Inspired by @sundaycrafts when he attempted to support TailwindCSS #100.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/8603085/170770146-fdf394c2-90cb-4d4f-9d58-a6535d137492.png">

@ntt261298 Can you give me your thought on this?

**Comment by nvh95** [comment]
**Draft Roadmap:**
- 0.2.4: add a nice console.warning (yellow) to users if they configure `externalCss`, show link to the migration guide
- 0.3.0: Remove the code to process `externalCss` in `jestPreviewConfigure`, add a error console.error (red), , show link to the migration guide
- 0.4.0: Throw an error if users configure `externalCss`, show link to the migration guide.

**Comment by ryota-murakami** [comment]
I like this change, just use Jest feature is straightforward rather than wrapper interface!
