### ISSUE TITLE
Test preview from example broken (Issue on Linux)

### ISSUE THREAD

**Issue by benoitgrasset-alma** [nvh95/jest-preview#138]
I tried to run the test from the example here: https://stackblitz.com/edit/jest-preview?file=src%2F__tests__%2FApp.test.tsx

I always get this error:

```
No preview found.
Please run:

preview.debug();
```

even on refresh and when i launch: `npm run test`

**Comment by nvh95** [comment]
Hi @benoitgrasset-alma,

Thanks for reaching us. Because of some technical limitations on stackblitz.com, Jest Preview couldn't "auto-refresh" the embedded browsers (WebContainer). Please hit the reload button to reload it manually. Please refer to my screen recording
https://user-images.githubusercontent.com/8603085/172909719-e06a2865-196b-4b30-9a98-9ac20d57aff9.mov
In short, you need to
1. `npm run jest-preview`
2. `npm run test`
3. Hit reload on the embedded browser (WebContainer)

Please let me know if you can run the demo on https://stackblitz.com/edit/jest-preview?file=README.md

Thanks.

**Comment by benoitgrasset-alma** [comment]
Thanks @nvh95 for your quick and clear answer :) I can run the demo too, like you showed me on your screen record, but I can't see the UI being updated in live with userEvent, like in the demo: [here](https://user-images.githubusercontent.com/8603085/162563155-7e18c9ef-4fe3-45f2-9065-7fcea8ddb18e.gif)

**Comment by nvh95** [comment]
@benoitgrasset-alma Yeah. That's something with stackblitz.com that I couldn't do anything. If you run it on your local machine, it will work fine.
Can you try on your local and confirm the UI is being updated in live?

**Comment by nvh95** [comment]
I also noted in the [README](https://stackblitz.com/edit/jest-preview?file=README.md) about the limitation:
> Hit Reload in the embeded browser. You should see the preview!
   (Since Stackblitz can't reload the embeded browser on file changes. On local machine, browser reloads instantly.)

**Comment by benoitgrasset-alma** [comment]
I tried on my local machine, with `v16.13.2` node version, chrome latest version, ubuntu 22.04, and i still don't have the HMR updates, only the satic UI running on port 3336
I tried this example: https://github.com/nvh95/jest-preview/tree/main/examples/vite-react

**Comment by nvh95** [comment]
What do you mean by `HMR`? Currently, Jest Preview hasn't had HMR feature yet. Whenever `debug()` is executed, the tab in `http://localhost:3336` reloads automatically to show an updated snapshot. And currently, it's a static UI only (we want to make it a fully functional app but we are not there yet #84).

Can you help to record a short video please? It should really help.

Thanks.

**Comment by benoitgrasset-alma** [comment]
here is my screen recorded: 

https://user-images.githubusercontent.com/104012464/173087687-65765dd9-ede8-4bd1-9dec-9799a0fbf9a7.mp4

**Comment by nvh95** [comment]
@benoitgrasset-alma Thank you for your recording. It's weird. Let me try to reproduce it on Ubuntu.
In the mean time, the "auto refresh" is implemented by a **web socket** server. Whenever `http://localhost:3336` receive an event ``{type: "reload"}``, it will reload. Can you help to investigate by checking if there is an event `{type: "reload"}` in `WS` subtab in `Network` tab, from Google Devtools, when you re-run your test?
<img width="1440" alt="jest preview websocket" src="https://user-images.githubusercontent.com/8603085/173089730-d2640680-2ca6-453b-b348-7a868b112203.png">

**Comment by benoitgrasset-alma** [comment]
I have no event:
![Capture d’écran du 2022-06-10 16-52-14](https://user-images.githubusercontent.com/104012464/173092306-4e29fb43-a851-4c55-b5ef-f5eea52720f6.png)

**Comment by nvh95** [comment]
@benoitgrasset-alma Thank you very much. Let me find an Ubuntu to reproduce to see if I see the same issue. If not, we might ask you for some additional information.

Thank you again.

**Comment by benoitgrasset-alma** [comment]
You're welcome, do not hesitate,
I use google chrome `Version 102.0.5005.61 (Build officiel) (64 bits)`

**Comment by benoitgrasset-alma** [comment]
@nvh95 did you have time to investigate and test on linux ?

**Comment by nvh95** [comment]
Hi @benoitgrasset-alma. I haven’t had a chance to reproduce it yet. I will let you know as soon as possible when we find something. Thanks.

**Comment by nvh95** [comment]
The possible root cause is explained here.
https://github.com/nvh95/jest-preview/pull/199#issuecomment-1186088862

**Comment by nvh95** [comment]
@benoitgrasset-alma Hi Benoit. We investigate and fix this issue on Linux in #200. Can you help to update `jest-preview` to version `>= 0.2.8` and then let us know if this issue is resolved on your Linux machine?

Thank you very much.

**Comment by benoitgrasset-alma** [comment]
Hi @nvh95, good job it solved the issue ! I just had to add `postcss-modules": "^4.3.1` to _package.json_

**Comment by nvh95** [comment]
Thank you @benoitgrasset-alma for reporting it 
@all-contributors pmease add @benoitgrasset-alma for bug
