### ISSUE TITLE
Add Angular

### ISSUE THREAD

**Issue by nvh95** [nvh95/jest-preview#170]
## What is the framework/ technology you want to integrate Jest Preview to?
Angular

## Useful links
- https://angular.io/
- https://testing-library.com/docs/angular-testing-library/intro

## Do you want to add this example on your own?
I need help.

**Comment by LayZeeDK** [comment]
@nvh95 @ntt261298 
Here's an example using Angular CLI with Jest via [@angular-builders/jest](https://www.npmjs.com/package/@angular-builders/jest):
https://github.com/LayZeeDK/nvh95-jest-preview/tree/LayZeeDK/docs/add-angular-example/examples/angular

I just read the raw global CSS stylesheet and append it to the document. I don't know how we would add Sass support although it is supported by Angular CLI.

Additionally, it would be interesting to run Angular in development mode to enable Angular Developer Tools.

I plan to add an Angular Testing Library example even though Angular's built-in `TestBed` API seems to work well.
