### ISSUE TITLE
Update docs Introduction section

### ISSUE THREAD

**Issue by skirianov** [nvh95/jest-preview#191]
## Which feature you want to improve?

Documentation Introduction section.

## What and why you want to improve that feature

It's quite short and doesn't really "buy" potential users. 

Points to improve: 
- Write better wording and explain the ideology of the project briefly.
- Try to fix the online playground to enable hot reload

## Potential bugs/ unexpected behaviors

N/A

## How to implement the changes

Check the examples of great documentation and implement similar techniques.

## Others

N/A

**Comment by skirianov** [comment]
@nvh95 as an additional suggestion is to remove **Features** section completely and add it to the **Introduction** section. 

Will add as separate commit, so we can revert easily if you won't like it ;)

**Comment by nvh95** [comment]
@skirianov 
> Write better wording and explain the ideology of the project briefly.

Absolutely agree

> as an additional suggestion is to remove Features section completely and add it to the Introduction section.

I am not very sure at the moment. But I still like the idea of having a separate `Features` section. We can still mention the features in the Introduction. But if someone doesn't want to read the long text, they can just navigate to the `Features` page.

Similar docs that have Features pages:
- https://vitejs.dev/guide/features.html
- https://vitest.dev/guide/features.html
- https://nextjs.org/docs/basic-features/pages

What do you think?

**Comment by nvh95** [comment]
@skirianov Wow. It looks incredible 💪💪🦾🦾. Indulge me with your draft PR 😹😹
