### ISSUE TITLE
Don't use hard-coded localhost for websocket

### ISSUE THREAD

**Issue by davidhao3300** [nvh95/jest-preview#258]
## Describe the bug

localhost is hard-coded here: https://github.com/nvh95/jest-preview/blob/v0.3.1/cli/server/ws-client.js#L4

This makes remote development a little more finicky. I'm running jest-preview in a remote server, and want to use my laptop's browser to visit the jest preview dashboard. Right now the dashboard loads fine, but since the websocket client tries to hit localhost, the auto-reloading doesn't work. I haven't tried it, but I believe a SSH tunnel would work around the issue, but would prefer not have to set that up.

I manually replaced localhost with my remote server's address, and things worked great

## Screenshots

N/A

## Reproduce

On a remote server with ports 3336 and 3337 available, run `yarn jest-preview`. Attempt to visit the remote IP at port 3336. Note that the JS console says that it tries to reach localhost:3337

## Expected behavior

I think the simplest and almost-strictly-better than current state is to use the browser host (window.host or whatever) as the hostname. For people using localhost, things will continue to work like before, while those using non-localhost should now automatically work, assuming that port 3337 is reachable.

There is an edge case for people who use 3336 with a remote hostname, but need a localhost 3337 for some reason...

## Environment (please complete the following information)

Running yarn jest-preview on a remote server, 0.3.1

**Comment by nvh95** [comment]
Hi @davidhao3300 

Thanks for your report. I published version `v0.3.2-alpha.0` to fix this. Can you try again with that version? I will incorporate a few other updates and release them all at once soon.

```
npm install --save-dev jest-preview@v0.3.2-alpha.0
```

> There is an edge case for people who use 3336 with a remote hostname, but need a localhost 3337 for some reason...

For now the PORT for `jest-preview` is `3336` and the port for socket connection is `PORT+1` (e.g: `3337`). Users can customize it my specify a custom port (e.g: `PORT=3761 npm run jest-preview`). I would like to find available ports automatically but haven't done yet. For now it's a low priority and we are happy to have the help of the community.

**Comment by davidhao3300** [comment]
I will give the new version a try today, thank you. The diff does look good to me!

**Comment by nvh95** [comment]
@davidhao3300 Thanks. I am looking forward to your confirmation.

**Comment by davidhao3300** [comment]
Looks good to me, thank you!
