### ISSUE TITLE
For a CRA app after following the instructions I got "sass not found. please install sass and try again."

### ISSUE THREAD

**Issue by Rohitbels** [nvh95/jest-preview#263]
For a CRA app after following the instructions I got "sass not found. please install sass and try again."

Once I installed sass additionally it worked.
But why was this required.

## Environment (please complete the following information)
- Jest version: [e.g. 26.6.0]

**Comment by ntt261298** [comment]
Hi @Rohitbels 

Thanks for reporting this. `jest-preview` doesn't require `sass` to work if your project doesn't contain `.scss` or `.sass` files. Does your project use sass? If not, can you check if you unintentionally import `.scss`, `.sass` file in the `jest-preview` [global CSS](https://www.jest-preview.com/docs/getting-started/installation/#4-optional-configure-global-css) . Also, it would be great if you can provide a reproduction, it will help us debug easier.

Thanks.

**Comment by Rohitbels** [comment]
Hey Sorry the issue was on our end.
Closing
