### ISSUE TITLE
Testing `jest-preview` in multiple platforms

### ISSUE THREAD

**Issue by nvh95** [nvh95/jest-preview#28]
# What & Why
- `jest-preview` is developed and tested on macOS. So we are not sure if it works on other platforms:
  - OS: Windows, linux...
  - Monorepo: lerna, turborepo...
# How
- We should find a way to make sure this library works on other platforms:
  - Seeking helps from contributors to test on other platforms
  - Setup CI/CD to run tests automatically

**Comment by nvh95** [comment]
@all-contributors please add @ntbinh-Harvey for test

**Comment by ParamagicDev** [comment]
Hi there! I'm currently running Jest + Jest-Preview in WSL. I've tried using the `npm-run-all` approach, running the `jest-preview` server separately, and calling the manual `debug()` vs `jestPreviewConfigure({ autoPreview: true })` and none of the approaches seems to work. I imagine its probably something to do with WSL, but figured I'd report it here! I'll work on getting a reproduction in place.

**Comment by ParamagicDev** [comment]
@nvh95 The only current reproduction I have is my Shadow Dom Testing library here:

https://github.com/ParamagicDev/shadow-dom-testing-library

it should be just:

```console
git clone https://github.com/ParamagicDev/shadow-dom-testing-library
cd shadow-dom-testing-library
npm install

# Modify a file to include the jest-preview
npm run test
```

**Comment by nvh95** [comment]
@ParamagicDev Can you please update `jest-preview` to the newest version (`>= 0.2.8`) then try again. We fix that issue in https://github.com/nvh95/jest-preview/pull/200.
Thanks.

**Comment by nvh95** [comment]
We tested the core function of `jest-preview` on
- [x] Mac (development machine)
- [x] Ubuntu
- [x] Windows

We also have CI to run on Ubuntu and Windows (GitHub Actions)

We also run it in some monorepo.
