### ISSUE TITLE
Can't install with the project inside the folder have a non breaking space in name

### ISSUE THREAD

**Issue by tinhvqbk** [nvh95/jest-preview#94]
**Describe the bug**
Can't install with the project inside the folder have a non breaking space in name
**To Reproduce**
- Give the project on the folder like: ~/Example Folder/my-project 
- Install `jest-preview` via command line `npm install --save jest-preview`

**Expected behavior**
Can install without error
**Screenshots**
![image](https://user-images.githubusercontent.com/26925018/165896528-8919667d-ad49-4aad-a249-79fee5ebe94d.png)

**Environment (please complete the following information)**

- OS: MacOS 11.6.1
- Jest version: 0.1.6

**Comment by nvh95** [comment]
Thank @tinhvqbk. Confirmed it's a bug. I will fix this in the next version

**Comment by nvh95** [comment]
@tinhvqbk This bug is fixed in https://www.npmjs.com/package/jest-preview/v/0.1.7

**Comment by nvh95** [comment]
@all-contributors please add @tinhvqbk for bug
